export { getSupabaseClient } from './supabase'
export { useAuthService, authUtils } from './authService'
export { useContact } from './contactService'
export { useClinic, clinicUtils } from './clinicService'
export { AppointmentService } from './appointmentService'
export type { SignUpData, SignInData, AuthResponse } from '@/types'
export type { ContactMessage, ContactResponse } from './contactService'
export type { ClinicResponse, ClinicsResponse } from './clinicService'
export type { Appointment, AppointmentFilters } from '@/types'
